version: '2'
services:
  bootstrap:
    build: monitored-geth-client
    restart: on-failure
    container_name: bootstrap
    hostname: bootstrap
    links:
      - netstats
    entrypoint: /root/start.sh
    command: '--networkid=42 --shh --nodekeyhex=091bd6067cb4612df85d9c1ff85cc47f259ced4d4cd99816b14f35650f59c322 --rpcapi "db,personal,eth,net,web3,shh" --rpccorsdomain="*" --rpc --rpcaddr="0.0.0.0"'
    volumes:
      - ./data:/root/.ethereum:rw
      - ./files/password:/root/files/password:ro
      - ./files/genesis.json:/root/files/genesis.json:ro
      - ./files/keystore:/root/.ethereum/keystore:rw
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
  eth:
    build: monitored-geth-client
    restart: on-failure
    links:
      - bootstrap
      - netstats
    entrypoint: /root/start.sh
    volumes:
      - ./files/password:/root/files/password:ro
      - ./files/genesis.json:/root/files/genesis.json:ro
      - ./files/keystore:/root/.ethereum/keystore:rw
      - /etc/localtime:/etc/localtime:ro
      - ./ethash:/root/.ethash:rw

    command: '--networkid=42 --shh --rpccorsdomain="*" --rpc --bootnodes="enode://288b97262895b1c7ec61cf314c2e2004407d0a5dc77566877aad1f2a36659c8b698f4b56fd06c4a0c0bf007b4cfb3e7122d907da3b005fa90e724441902eb19e@XXX:30303"'
  netstats:
    build: eth-netstats
    restart: on-failure
    container_name: netstats
    environment:
      - WS_SECRET=eth-net-stats-secret
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
